import type { ColorTheme } from '../types';

export const volcengineDesignColors: ColorTheme = {
  'input.border.error': { fallbackHex: '#D7312A' },
  'input.border.active': { fallbackHex: '#1664FF' },
  'input.border.hover': { fallbackHex: '#86909C' },
  'input.border': { fallbackHex: '#DDE2E9' },
  'input.disabled.text': { fallbackHex: '#C9CDD4' },
  'input.affix': { fallbackHex: '#737A87' },
  'card.title.form': { fallbackHex: '#0C0D0E' },
  'card.title.card': { fallbackHex: '#000000' },
  'layout.border': { fallbackHex: '#EAEDF1' },
  'form.label': { fallbackHex: '#42464E' },
  'form.help': { fallbackHex: '#737A87' },
  'form.error.text': { fallbackHex: '#F5222D' },
  'table.header.bg': { fallbackHex: '#F5F5F5' },
  'table.cell.bg': { fallbackHex: '#FFFFFF' },
  'table.border': { fallbackHex: '#EAEDF1' },
  'table.cell.text': { fallbackHex: '#0C0D0E' },
  'table.header.text': { fallbackHex: '#42464E' },
  'table.action.danger': { fallbackHex: '#D7312A' },
  'table.action.primary': { fallbackHex: '#1664FF' },
  'table.action.icon': { fallbackHex: '#42464E' },
  'text.placeholder': { fallbackHex: '#999999' },
  'text.primary': { fallbackHex: '#0C0D0E' },
  'button.secondary.bg': { fallbackHex: '#E6E6E6' },
  'button.primary.bg': { fallbackHex: '#1890FF' },
  'button.secondary.text': { fallbackHex: '#333333' },
  'button.outline.text': { fallbackHex: '#1890FF' },
  'button.primary.text': { fallbackHex: '#FFFFFF' },
  'radio.bg': { fallbackHex: '#FFFFFF' },
  'radio.selected.border': { fallbackHex: '#1664FF' },
  'radio.border': { fallbackHex: '#EAEDF1' },
  'radio.dot': { fallbackHex: '#1664FF' },
  'radio.label': { fallbackHex: '#0C0D0E' },
  'card.bg': { fallbackHex: '#FFFFFF' },
  'fallback.color': { fallbackHex: '#CCCCCC' },
  'chart.title': { fallbackHex: '#0C0D0E' },
  'chart.label': { fallbackHex: '#737A87' }
};
